oracle cloud

diff --git a/.github/workflows/prod.yaml b/.github/workflows/prod.yaml
--- a/.github/workflows/prod.yaml
+++ b/.github/workflows/prod.yaml
@@ -33,13 +33,89 @@ jobs:
           name: GitHub_Actions-prd
           path: production
 
-      - name: Login to Heroku Container registry
-        env:
-          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
-        run: heroku container:login
+      #      - name: Login to Heroku Container registry
+      #        env:
+      #          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
+      #        run: heroku container:login
+      #
+      #      - name: Build and push
+      #        env:
+      #          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
+      #          HEROKU_APP_NAME: github-actions-example
+      #        run: heroku plugins:install java && heroku create --no-remote && heroku deploy:jar production/eventos-da-rep-api-0.1-all.jar --app eventos-da-rep-api
 
-      - name: Build and push
-        env:
-          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
-          HEROKU_APP_NAME: github-actions-example
-        run: heroku plugins:install java && heroku create --no-remote && heroku deploy:jar production/eventos-da-rep-api-0.1-all.jar --app eventos-da-rep-api
+      - name: 'Write Config & Key Files'
+        run: |
+          mkdir ~/.oci
+          echo "[DEFAULT]" >> ~/.oci/config
+          echo "user=${{secrets.OCI_USER_OCID}}" >> ~/.oci/config
+          echo "fingerprint=${{secrets.OCI_FINGERPRINT}}" >> ~/.oci/config
+          echo "pass_phrase=${{secrets.OCI_PASSPHRASE}}" >> ~/.oci/config
+          echo "region=${{secrets.OCI_REGION}}" >> ~/.oci/config
+          echo "tenancy=${{secrets.OCI_TENANCY_OCID}}" >> ~/.oci/config
+          echo "key_file=~/.oci/key.pem" >> ~/.oci/config
+          echo "${{secrets.OCI_KEY_FILE}}" >> ~/.oci/key.pem
+
+      - name: 'Install OCI CLI'
+        run: |
+          curl -L -O https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh
+          chmod +x install.sh
+          ./install.sh --accept-all-defaults
+          echo "::add-path::/home/runner/bin"
+          exec -l $SHELL
+
+      - name: 'Fix Config File Permissions'
+        run: |
+          oci setup repair-file-permissions --file /home/runner/.oci/config
+          oci setup repair-file-permissions --file /home/runner/.oci/key.pem
+
+      - name: 'Get Instance IP'
+        run: |
+          echo "::set-env name=INSTANCE_IP::$( \
+            oci compute instance list-vnics \
+            --instance-id ${{env.INSTANCE_OCID}} \
+            --query 'data [0]."public-ip"' \
+            --raw-output \
+          )"
+
+      - name: 'Wait for SSH'
+        run: |
+          while ! nc -w5 -z ${{ env.INSTANCE_IP }} 22; do
+                  sleep 5
+                  echo "SSH not available..."
+          done; echo "SSH ready!"
+
+      - name: 'Stop App'
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{env.INSTANCE_IP}}
+          username: opc
+          key: ${{secrets.VM_SSH_PRIVATE_KEY}}
+          script: |
+            pid=`ps aux | grep "[c]icd-demo.jar" | awk '{print $2}'`
+            if [ "$pid" == "" ]; then
+              echo "Process not found"
+            else
+              kill -9 $pid
+            fi
+            sudo mkdir -p /app
+
+      - name: 'Push JAR'
+        uses: appleboy/scp-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: opc
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          source: "build/libs/cicd-demo-${{env.VERSION}}-all.jar"
+          target: "app"
+          strip_components: 2
+
+      - name: 'Start App'
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ env.INSTANCE_IP }}
+          username: opc
+          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
+          script: |
+            sudo mv ~/app/cicd-demo-${{env.VERSION}}-all.jar /app/cicd-demo.jar
+            nohup java -jar /app/cicd-demo.jar > output.$(date --iso).log 2>&1 &
